---
- hosts: sensu-backend-server
  become: true

  vars:
    server: True

    slack: True
    slack_webhook_url: https://hooks.slack.com/services/xxx
    slack_channel: "@elias"
    sensu_client_subs:
        - linux
    sensu_cluster: True

    etcd_advertise_client_urls: "http://{{ ansible_enp0s8.ipv4.address }}:2379"
    etcd_initial_advertise_peer_urls: "http://{{ ansible_enp0s8.ipv4.address }}:2380"
    etcd_initial_cluster:
      - "backend-1=http://192.168.88.100:2380"
      - "backend-2=http://192.168.88.101:2380"
      - "backend-3=http://192.168.88.102:2380"

    etcd_initial_cluster_state: "new" # new or existing
    etcd_initial_cluster_token: " "
    etcd_listen_client_urls: "http://{{ ansible_enp0s8.ipv4.address }}:2379"
    etcd_listen_peer_urls: "http://0.0.0.0:2380"
    etcd_name: "{{ ansible_hostname }}"

  roles:
    - role: ansible-sensu-go

- hosts: sensu-agent
  become: true
  vars:
    server: False
    sensu_client_subs:
        - linux

    backend_url:
        - "ws://192.168.88.100:8081"
        - "ws://192.168.88.101:8081"
        - "ws://192.168.88.102:8081"

  roles:
    - role: ansible-sensu-go
